### ISSUE TITLE
微信骁龙晓友会怎么抓包？

### ISSUE THREAD

**Issue by 1125197567** [smallfawn/QLScriptPublic#121]
TypeError: Cannot read properties of undefined (reading 'code')
    at UserInfo.task_signIn (/ql/data/scripts/骁龙.swap.js:75:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async UserInfo.main (/ql/data/scripts/骁龙.swap.js:36:13)
    at async start (/ql/data/scripts/骁龙.swap.js:137:26)
    at async /ql/data/scripts/骁龙.swap.js:146:9
"unable to verify the first certificate"

**Comment by smallfawn** [comment]
估计脚本失效了

**Comment by 3238614968** [comment]
![image](https://github.com/smallfawn/QLScriptPublic/assets/88702174/2ed3fba3-acfa-43c8-b159-d7f82228b042)
没问题啊
