### ISSUE TITLE
hi星途

### ISSUE THREAD

**Issue by maech01** [smallfawn/QLScriptPublic#138]
今天已签到🎉
Error: Cannot find module 'encryptlong'
Require stack:
- /ql/data/scripts/smallfawn_QLScriptPublic/exeedcars.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at jsencrtpt_result (/ql/data/scripts/smallfawn_QLScriptPublic/exeedcars.js:376:35)
    at UserInfo.creat_content (/ql/data/scripts/smallfawn_QLScriptPublic/exeedcars.js:414:23)
    at UserInfo.art_list (/ql/data/scripts/smallfawn_QLScriptPublic/exeedcars.js:319:32)
    at UserInfo.main (/ql/data/scripts/smallfawn_QLScriptPublic/exeedcars.js:52:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async start (/ql/data/scripts/smallfawn_QLScriptPublic/exeedcars.js:441:26) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/ql/data/scripts/smallfawn_QLScriptPublic/exeedcars.js' ]
}
TypeError: Cannot read properties of undefined (reading '0')
    at UserInfo.main (/ql/data/scripts/smallfawn_QLScriptPublic/exeedcars.js:63:105)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async start (/ql/data/scripts/smallfawn_QLScriptPublic/exeedcars.js:441:26)
    at async /ql/data/scripts/smallfawn_QLScriptPublic/exeedcars.js:451:9
怎么回事呢？

**Comment by smallfawn** [comment]
安装encryptlong  nodejs依赖

**Comment by maech01** [comment]
> 安装encryptlong  nodejs依赖

依赖安装了，还是这个问题呢？

**Comment by smallfawn** [comment]
不可能吧

**Comment by maech01** [comment]
> 不可能吧

py3.10跑不动py3.11可以

**Comment by smallfawn** [comment]
不好意思，我的是js脚本，和Python有什么关系吗

**Comment by maech01** [comment]
> 不好意思，我的是js脚本，和Python有什么关系吗

那不知道2.10.13，可以跑，2。15。17跑不动
