### ISSUE TITLE
我来提个issue，凯翼汽车

### ISSUE THREAD

**Issue by moliyadi007** [smallfawn/QLScriptPublic#2]
签到成功
TypeError: console[_0x513b1b(...)](...) is not a function
    at JobTask.doTask (/ql/scripts/smallfawn_QLScriptPublic/凯翼汽车.js:19:69987)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /ql/scripts/smallfawn_QLScriptPublic/凯翼汽车.js:19:79169

**Comment by smallfawn** [comment]
目测青龙版本太低 推荐不低于2.11.3

**Comment by Huansheng1** [comment]
一天可以设定多次，貌似第一次可能会出现这个问题，第二次开始就不会了
