### ISSUE TITLE
bnmdhg_wx.js报错

### ISSUE THREAD

**Issue by jaychoubaby** [smallfawn/QLScriptPublic#214]
账号[3]  签到: 失败
  <!DOCTYPE html>
  <html lang="zh-cn">

  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="data-spm" content="a3c0e" />
    <title>405</title>
    <style>
      html, body, div, a, h2, p { margin: 0; padding: 0;  }
      a { text-decoration: none; color: #3b6ea3;  }
      .container { width: 1000px; margin: auto; color: #696969; }
      .header { padding: 110px 0; }
      .header .message { height: 36px; padding-left: 120px; background: url(https://errors.aliyun.com/images/TB1TpamHpXXXXaJXXXXeB7nYVXX-104-162.png) no-repeat 0 -128px; line-height: 36px; }
      .main { padding: 50px 0; background: #f4f5f7; }
      .main img { position: relative; left: 120px; }
      .footer { margin-top: 30px; text-align: right; }
      .footer a { padding: 8px 30px; border-radius: 10px; border: 1px solid #4babec; }
      .footer a:hover { opacity: .8; }
      .alert-shadow { display: none; position: absolute; top: 0; left: 0; width: 100%; height: 100%; background: #999; opacity: .5; }
      .alert { display: none; position: absolute; top: 200px; left: 50%; width: 600px; margin-left: -300px; padding-bottom: 25px; border: 1px solid #ddd; box-shadow: 0 2px 2px 1px rgba(0, 0, 0, .1); background: #fff; font-size: 14px; color: #696969; }
      .alert h2 {  margin: 0 2px; padding: 10px 15px 5px 15px; font-size: 14px; font-weight: normal; border-bottom: 1px solid #ddd; }
      .alert a { display: block; position: absolute; right: 10px; top: 8px; width: 30px; height: 20px; text-align: center; }
      .alert p {  padding: 20px 15px; }
    </style>
  </head>

  <body data-spm="7663354">
    <div data-spm="1998410538">
      <div class="header">
        <div class="container">
          <div class="message">
            很抱歉，由于您访问的URL有可能对网站造成安全威胁，您的访问被阻断。
            <div>当前网址: <strong id="url"></strong></div>
            <div>请求时间: <strong id="time"></strong></div>
            <div>请求ID: <strong id="traceid"></strong></div>
          </div>
        </div>
      </div>
      <div class="main">
        <div class="container">
          <img src="https://errors.aliyun.com/images/TB15QGaHpXXXXXOaXXXXia39XXX-660-117.png" />
        </div>
      </div>
      <div class="footer">
        <div class="container">
          <a target="_blank" id="report" href="javascript:;" data-spm-click="gostr=/waf.123.123;locaid=d001;">误报反馈</a>
        </div>
      </div>
    </div>
    <div id="alertShadow" class="alert-shadow"></div>
    <div id="alertContainer" class="alert">
      <h2>提示：<a href="javascript:;" title="关闭" id="closeAlert">X</a></h2>
      <p>感谢您的反馈，应用防火墙会尽快进行分析和确认。</p>
    </div>
    <script>
      function show() {
        var g = function(ele) { return document.getElementById(ele); };
        var reportHandle = g('report');
        var alertShadow = g('alertShadow');
        var alertContainer = g('alertContainer');
        var closeAlert = g('closeAlert');
        var own = {};
        own.report = function() {
          // SPM
          own.alert();
        };
        own.alert = function() {
          alertShadow.style.display = 'block';
          alertContainer.style.display = 'block';
        };
        own.close = function() {
          alertShadow.style.display = 'none';
          alertContainer.style.display = 'none';
        };
      };
      function getRenderData(){
          var tagStart = "renderData:"
          var dataTag = document.getElementById('renderData')
          var renderData = JSON.parse(dataTag.innerHTML)
          return renderData
      }

      function convertTimestampToString(timestampStr) {
          var timestamp = parseInt(timestampStr, 10);
          var date = new Date(timestamp);

          // 构建日期和时间的字符串
          var year = date.getFullYear();
          var month = ("0" + (date.getMonth() + 1)).slice(-2); // 月份从0开始，所以需要+1
          var day = ("0" + date.getDate()).slice(-2);
          var hours = ("0" + date.getHours()).slice(-2);
          var minutes = ("0" + date.getMinutes()).slice(-2);
          var seconds = ("0" + date.getSeconds()).slice(-2);

          return year + '-' + month + '-' + day + ' ' + hours + ':' + minutes + ':' + seconds;
      }
      window.onload=function(){

          var renderData = getRenderData()
          if(renderData){
              var traceid = renderData["traceid"]
              var timestr = traceid.slice(8,21)
              document.getElementById("traceid").innerText = traceid
              document.getElementById("url").innerText = location.href.split('?')[0]
              document.getElementById("time").innerText = convertTimestampToString(timestr)
          }
      }
    </script>
  </body>
  </html>
  <textarea id="renderData" style="display:none">
{"traceid": "0a5cc90217209422136323149e3cdb"}</textarea>

**Comment by jaychoubaby** [comment]
上面是qx上跑报错，下面是青龙跑报错：

```
TypeError: Cannot read properties of undefined (reading 'code')
    at _0x4692a1.sign_in (/ql/data/scripts/back/bnmdhg_wx.js:10:43734)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _0x4692a1.sign_info (/ql/data/scripts/back/bnmdhg_wx.js:10:42459)
```

**Comment by 799814488** [comment]
post请求失败

❗️巴奴火锅小程序,错误!

TypeError: Cannot read properties of undefined (reading 'code')
    at _0x4692a1.sign_in (/ql/data/scripts/smallfawn_QLScriptPublic/bnmdhg_wx.js:10:43734)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _0x4692a1.sign_info (/ql/data/scripts/smallfawn_QLScriptPublic/bnmdhg_wx.js:10:42459)

**Comment by smallfawn** [comment]
过几天修复
