### ISSUE TITLE
巴奴火锅签到失败

### ISSUE THREAD

**Issue by S091** [smallfawn/QLScriptPublic#221]
显示已经签到成功，但实际没有签到，麻烦大佬抽空看一下

**Comment by smallfawn** [comment]
修复了

**Comment by jaychoubaby** [comment]
> 修复了

账号[2]  已签到80天 获得积分为40🎉
❌账号[2]  签到: 失败
[object Object]

**Comment by S091** [comment]
> 修复了

刚试了试还是不行，还有个别账号还有报错，重新抓了token了，下面是报错信息
TypeError: Cannot read properties of undefined (reading 'code')
    at _0x4692a1.sign_in (/ql/scripts/smallfawn_QLScriptPublic/bnmdhg_wx.js:10:43734)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async _0x4692a1.sign_info (/ql/scripts/smallfawn_QLScriptPublic/bnmdhg_wx.js:10:42459)

**Comment by checkToke** [comment]
https://github.com/checkToke/yangtai.git  这里的可以
