### ISSUE TITLE
巴奴火锅小程序 签到post请求失败 显示有签到 实际没成功

### ISSUE THREAD

**Issue by Ytong825** [smallfawn/QLScriptPublic#222]
post请求失败

❗️巴奴火锅小程序,错误!

TypeError: Cannot read properties of undefined (reading 'code')
    at _0x4692a1.sign_in (/ql/data/scripts/smallfawn_QLScriptPublic/bnmdhg_wx.js:10:43734)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _0x4692a1.sign_info (/ql/data/scripts/smallfawn_QLScriptPublic/bnmdhg_wx.js:10:42459)

**Comment by smallfawn** [comment]
修复了

**Comment by curx95** [comment]
> 修复了

{
  code: 4001,
  message: '入参信息有误: "member_id" is not allowed',
  data: null,
  success: false,
  request_id: '669ff3b8e08e597c119a4351'
} 测试了下，还是有问题的。member_id难道改了？

**Comment by wxyShine** [comment]
你好 bnmdhg_wx.js 这个有使用说明吗?
