### ISSUE TITLE
云闪付签到好像挂了？

### ISSUE THREAD

**Issue by monobo1989** [smallfawn/QLScriptPublic#239]
云闪付签到好像挂了？

**Comment by xujinhui2015** [comment]
我也是挂了：
post请求失败

❗️云闪付签到,错误!

TypeError: Cannot use 'in' operator to search for 'signedIn' in undefined
    at UserInfo.sign (/ql/data/scripts/smallfawn_QLScriptPublic/ysfqd.js:58:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async start (/ql/data/scripts/smallfawn_QLScriptPublic/ysfqd.js:29:26)
    at async /ql/data/scripts/smallfawn_QLScriptPublic/ysfqd.js:74:9

**Comment by zadishu** [comment]
g挂了

**Comment by smallfawn** [comment]
过几天修复

**Comment by ruixule** [comment]
> 过几天修复

我用ipad 给云闪付抓包，开启stream 后，app 中页面都打不开

**Comment by monobo1989** [comment]
> 过几天修复

期待哦，大佬！
