### ISSUE TITLE
坦克TANK 日志提示结束了但是任务一直显示运行中

### ISSUE THREAD

**Issue by yanxinzi** [smallfawn/QLScriptPublic#48]
RT，有时候任务会2-3个小时才会自动停止

```
post请求失败

❗️坦克TANK, 错误!

TypeError: Cannot read properties of undefined (reading 'code')
    at UserInfo.task_signin (/ql/data/scripts/smallfawn_QLScriptPublic/Tank.js:17:9686)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async UserInfo.point_info (/ql/data/scripts/smallfawn_QLScriptPublic/Tank.js:17:7808)
    at async start (/ql/data/scripts/smallfawn_QLScriptPublic/Tank.js:17:3488)
    at async /ql/data/scripts/smallfawn_QLScriptPublic/Tank.js:17:16695
账号[1]总积分:410
账号[1]点赞成功，获得坦克币+2
账号[1]点赞成功，获得坦克币+2
账号[1]点赞成功，获得坦克币+2
账号[1]点赞成功，获得坦克币+2
账号[1]点赞成功，获得坦克币+2
Telegram发送通知消息成功🎉。


🔔坦克TANK, 结束! 🕛 38.416 秒
```

**Comment by qifengle1** [comment]
确实，我的也是，而且签到任务也出问题了，不会签到了
