### ISSUE TITLE
爱看热点执行报错了

### ISSUE THREAD

**Issue by yanxinzi** [smallfawn/QLScriptPublic#55]
RT
```
开始闯关
初始化广告
展示广告
模拟看广告
随机等待66s
get请求失败

❗️爱看热点,错误!

TypeError: Cannot read properties of undefined (reading 'success')
    at UserInfo.action_completed (/ql/data/scripts/smallfawn_QLScriptPublic/akrd.js:14:44620)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async UserInfo.barrierGet (/ql/data/scripts/smallfawn_QLScriptPublic/akrd.js:14:15109)
    at async UserInfo.checkCK (/ql/data/scripts/smallfawn_QLScriptPublic/akrd.js:14:17376)
    at async UserInfo.task (/ql/data/scripts/smallfawn_QLScriptPublic/akrd.js:14:11349)
    at async start (/ql/data/scripts/smallfawn_QLScriptPublic/akrd.js:14:8540)
    at async /ql/data/scripts/smallfawn_QLScriptPublic/akrd.js:14:45616
post请求失败
```

**Comment by smallfawn** [comment]
没有报错
