### ISSUE TITLE
吉利银河被禁言创建文章失败，不执行任务

### ISSUE THREAD

**Issue by loren-loren** [smallfawn/QLScriptPublic#79]
❌账号[1]  创建文章失败
{
  code: 'C00503',
  msg: '您已被禁言！',
  data: null,
  traceId: '2f624a0f16932076837394064e4ae5',
  success: false
}
TypeError: Cannot read properties of undefined (reading 'dynamic')
    at UserInfo.articleList (/ql/scripts/jlyh.js:421:82)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async UserInfo.main (/ql/scripts/jlyh.js:243:13)
    at async start (/ql/scripts/jlyh.js:27:26)
    at async /ql/scripts/jlyh.js:496:9
发布文章不成功，不执行评论 分享 删除

**Comment by smallfawn** [comment]
额 估计文章禁言了

**Comment by loren-loren** [comment]
大佬，能不做发布文章吗？

**Comment by smallfawn** [comment]
不做的话没有积分把
